name: Waka Readme

on:
  push:
    branches: [main]
  schedule:
    # Runs at 2am UTC
    - cron: '2 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_UPDATED_DATE: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "False"
          SHOW_SHORT_INFO: "False"
          SYMBOL_VERSION: "3"
          DEBUG_LOGGING: "True"
